main_app/urls.py
from django.urls import path
from . import views
from main_app.views import Index



urlpatterns = [
  path('', Index.as_view(), name='index'),
  path('crafts/', views.user_index, name='crafts'),
  path('search/', views.search, name='search'),
  path('form/', views.form, name='form'),
  path('create/', views.create, name='create'),
  path('favorite/', views.favorite_index, name='favorite_index'),
  path('favorite/<int:craft_id>', views.favorite_create, name='favorite_create'),
  path('crafts/<int:craft_id>/update', views.craft_update, name='craft_update'),
  path('crafts/<int:craft_id>/edit', views.edit, name='edit'),

  
  path('crafts/<int:pk>/detail', views.CraftDetail.as_view(), name='detail'),
  path('crafts/<int:pk>/delete', views.CraftDelete.as_view(), name='crafts_delete'),
  path('accounts/signup/', views.signup, name='signup'),
]

spacecrafts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator

# Create your models here.


class Badge(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    image = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Craft(models.Model):
    # from API
    cargo_capacity = models.BigIntegerField()
    consumables = models.CharField(max_length=100)
    cost_in_credits = models.BigIntegerField()
    crew = models.IntegerField()
    length = models.DecimalField(decimal_places=10, max_digits=20)
    manufacturer = models.CharField(max_length=500)
    max_atmosphering_speed = models.IntegerField()
    model = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    passengers = models.IntegerField()
    hyperdrive_rating = models.FloatField()
    url = models.CharField(max_length=100, default=None)
    # may or may not exist
    vehicle_class = models.CharField(max_length=100)
    starship_class = models.CharField(max_length=100)
    MGLT = models.CharField(max_length=100)
    # own stuff
    sell_price = models.IntegerField()
    BUCKET = 'Bucket'
    FAIR = 'Fair'
    GOOD = 'Good'
    EXCELLENT = 'Excellent'
    LIKE_NEW = 'Like New'
    CONDITION = (
        (BUCKET, 'Bucket'),
        (FAIR, 'Fair'),
        (GOOD, 'Good'),
        (EXCELLENT, 'Excellent'),
        (LIKE_NEW, 'Like New'),
    )
    condition = models.CharField(max_length=100, choices = CONDITION, default = GOOD)
    description = models.TextField(max_length=1000)
    mileage = models.IntegerField()
    date_created = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    badges = models.ManyToManyField(Badge)
    color = models.CharField(max_length=100, blank=True)
    black = models.CharField(max_length=100, blank=True)

    def __str__(self): 
        return self.name

    def get_absolute_url(self):
        return reverse('crafts')

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    craft = models.ForeignKey(Craft, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now=True)

    def __str__(self): 
        return f"{self.craft_id}"

class Photo(models.Model):
    url = models.CharField(max_length=200)
    craft = models.ForeignKey(Craft, on_delete=models.CASCADE)


    def __str__(self):
        return f"Photo for craft_id: {self.craft_id} @{self.url}"

class Image(models.Model):
    color = models.CharField(max_length=200)
    black = models.CharField(max_length=200)

main_app/forms.py
from django.forms import ModelForm
from .models import Craft

class CraftForm(ModelForm):
    class Meta:
        model = Craft
        # fields = ['cargo_capacity', 'consumables', 'cost_in_credits', 'crew', 'length', 'manufacturer', 'max_atmosphering_speed', 'model', 'name', 'passengers', 'hyperdrive_rating', 'vehicle_class', 'starship_class', 'MGLT', 'sell_price', 'condition', 'description', 'mileage'] 
        exclude = ['url', 'user', 'badges', 'black', 'color']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Craft, Favorite, Photo, Badge, Image
from .forms import CraftForm
from django.views.generic import ListView, UpdateView, DeleteView, DetailView
import requests
import uuid
import boto3
import os
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class Index(ListView):
    model = Craft
    fields = ['name']

    def get_context_data(self, **kwargs):
        if (not self.request.user.is_anonymous):
            context = super().get_context_data(**kwargs)
            library = []
            favs = Favorite.objects.filter(user = self.request.user)
            for fav in favs:
                library.append(fav.__dict__['craft_id'])
            context['favs'] = library
            return context
        else:
            context = super().get_context_data(**kwargs)
            context['object_list'] = Craft.objects.all()
            return context
            
    
        

@login_required
def user_index(request):
    crafts = Craft.objects.filter(user=request.user)
    return render(request, 'spacecrafts/index.html', { 'crafts': crafts })

@login_required
def search(request):
    images = Image.objects.all()
    response = requests.get('https://swapi.dev/api/starships')
    results = response.json()
    starships = results['results']
    for idx,val in enumerate(starships):
        val['color'] = images[idx].color
        val['black'] = images[idx].black
    response2 = requests.get('https://swapi.dev/api/vehicles')
    results2 = response2.json()
    vehicles = results2['results']
    for idx,val in enumerate(vehicles):
        val['color'] = images[idx+10].color
        val['black'] = images[idx+10].black
    starships = starships + vehicles
    return render(request, 'spacecrafts/search.html', { 'starships': starships })

@login_required
def form(request):
    color = request.POST["color"]
    black = request.POST["black"]
    response = requests.get(request.POST["url"])
    results = response.json()
    craft_form = CraftForm(results)
    badges = Badge.objects.all()
    return render(request, 'spacecrafts/form.html', { 'craft_form' : craft_form , 'url' : results['url'], 'badges' : badges, 'color' : color, 'black' : black}) #end point at url in request.post

@login_required
def create(request):
    form = CraftForm(request.POST)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.url = request.POST['url']
        instance.black = request.POST['black']
        instance.color = request.POST['color']
        instance.save()
        for badge in request.POST.getlist('badges'):
            instance.badges.add(int(badge))
        photo_file = request.FILES.get('photo-file', None)
        if photo_file:
            s3 = boto3.client('s3')
            key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
            try:
                bucket = os.environ['S3_BUCKET']
                s3.upload_fileobj(photo_file, bucket, key)
                url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                Photo.objects.create(url=url, craft_id=instance.__dict__['id'])
            except:
                print('An error occurred uploading file to S3')
    return redirect('crafts')

@login_required
def favorite_index(request):
    favs = request.user.favorite_set.all()
    return render(request, 'spacecrafts/favorite.html', { 'favs' : favs }) 

@login_required
def favorite_create(request, craft_id):
    favs = request.user.favorite_set.all()
    for fav in favs:
        if (craft_id == fav.__dict__['craft_id']):
            fav.delete()
            return redirect('index')
    else:
        instance = Favorite()
        instance.craft_id = craft_id
        instance.user = request.user
        instance.save()
        return redirect('index')


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def craft_update(request, craft_id):
    craft = Craft.objects.get(id=craft_id)
    if craft.__dict__['user_id'] == request.user.id:
        photos  = Photo.objects.filter(craft = craft_id)
        print(photos)
        badges_not = Badge.objects.exclude(id__in = craft.badges.all().values_list('id'))
        form = CraftForm(craft.__dict__)
        return render(request, 'main_app/craft_form.html', {'form' : form, 'craft' : craft, 'badges' : badges_not, 'photos': photos})
    else:
        return redirect('index')


def edit(request, craft_id):
    instance = Craft.objects.get(id=craft_id)
    form = CraftForm(request.POST, instance=instance)
    if form.is_valid():
        form.save()
        for badge in request.POST.getlist('badges'):
            instance.badges.add(int(badge))
        for badge in request.POST.getlist('badges_has'):
            instance.badges.remove(int(badge))
        for photo in request.POST.getlist('photos'):
            Photo.objects.get(id = photo).delete()
        photo_file = request.FILES.get('photo-file', None)
        if photo_file:
            s3 = boto3.client('s3')
            key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
            try:
                bucket = os.environ['S3_BUCKET']
                s3.upload_fileobj(photo_file, bucket, key)
                url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                Photo.objects.create(url=url, craft_id=instance.__dict__['id'])
            except:
                print('An error occurred uploading file to S3')
        return redirect('crafts')
    return redirect('crafts')

class CraftDelete(DeleteView, LoginRequiredMixin):
    model = Craft
    success_url = '/crafts/'

class CraftDetail(DetailView, LoginRequiredMixin):
    model = Craft
    fields = '__all__'

    def get_context_data(self, **kwargs):
        if (not self.request.user.is_anonymous):
            context = super().get_context_data(**kwargs)
            library = []
            favs = Favorite.objects.filter(user = self.request.user)
            for fav in favs:
                library.append(fav.__dict__['craft_id'])
            context['favs'] = library
            return context
        else:
            context = super().get_context_data(**kwargs)
            context['object_list'] = Craft.objects.all()
            return context

main_app/templates/main_app/craft_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1 tabindex="-1">Delete Craft</h1>
  <h4 tabindex="-1">Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
  <form tabindex="-1" action="" method="POST">
    {% csrf_token %}
    <input tabindex="1" type="submit" value="Yes - Delete!" class="btn">
  </form>
  <a href="{% url 'crafts' %}">Cancel</a>
{% endblock %}

main_app/templates/main_app/craft_detail.html
{% extends 'base.html' %}
{% block content %}
<h1 tabindex="-1">DETAIL <span class="teal-text">{{object.name}}</span></h1>
<div tabindex="-1" id="detail_container">
    <div tabindex="-1" class="carousel">
        {% for photo in craft.photo_set.all %}
                <a tabindex="-1" class="carousel-item">
                    <img tabindex="-1" alt="User uploaded photo."  src="{{photo.url}}">
                </a>
        {% empty %}
                <div tabindex="-1">No Photos Uploaded</div>
        {% endfor %}
    </div>
    <div>
        <div tabindex="-1">Model: {{ craft.model}}</div>
        <div tabindex="-1"> Manufacturer: {{ craft.manufacturer}}</div>
        <div tabindex="-1"> Price: {{ craft.price}}</div>
        <div tabindex="-1"> Mileage: {{ craft.mileage}}</div>
        <div tabindex="-1">  Consumables: {{ craft.consumables }}</div>
        <div tabindex="-1"> Cost in Credits: {{ craft.cost_in_credits}}</div>
        <div tabindex="-1"> Crew: {{ craft.crew}}</div>
        <div tabindex="-1"> Length: {{craft.length}}</div>
        <div tabindex="-1"> Max atmosphering speed: {{ craft.max_atmosphering_speed}}</div>
        <div tabindex="-1"> Name: {{craft.name}}</div>
        <div tabindex="-1"> Passengers: {{ craft.passengers}}</div>
        <div tabindex="-1"> Hyperdrive Rating: {{craft.hyperdrive_rating}}</div>
        <div tabindex="-1"> url: {{craft.url }}</div>
        <div tabindex="-1"> Vehicle class: {{ craft.vehicle_class}}</div>
        <div tabindex="-1"> Starship Class: {{craft.starship_class}}</div>
        <div tabindex="-1"> MGLT: {{ craft.mglt}}</div>
        <div tabindex="-1"> Sell Price: {{ craft.sell_price}}</div>
        <div tabindex="-1"> Condition: {{ craft.condtion}}</div>
        <div tabindex="-1"> Description: {{ craft.description}}</div>
        <div tabindex="-1"> Date Created: {{ craft.date_created}}</div>
        <div tabindex="-1" id="detail_badge">
            {% if craft.badges.count %}
                {% for badge in craft.badges.all %}
                <div tabindex="-1">
                    <img tabindex="-1" alt="Badge emblum." src="{{badge.image}}">
                    <p tabindex="-1">NAME: {{ badge.name }}</p>
                    <p tabindex="-1">description: {{ badge.description }}</p>
                </div>
                {% endfor %}
            {% else %}
                <p tabindex="-1">No Badges</p>
            {% endif %}
        </div>
        
        <div tabindex="-1" id="list_fav">
            {% if user.is_authenticated %}
                {% if craft.user.id != user.id %}
                    {% if craft.id in favs %}
                        <a class="fav_button" style="background-color:  #94849B" href="{% url 'favorite_create' craft.id %}"></a>
                    {% else %}
                        <a class="fav_button" href="{% url 'favorite_create' craft.id %}"></a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>

<a href="javascript:history.back()">Go Back</a>

<script >
    document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('.carousel');
    var instances = M.Carousel.init(elems, {
        numVisible : 4,
    });
});
</script>
{% endblock %}

main_app/templates/main_app/craft_form.html
{% extends 'base.html' %} {% block content %}
<h1 tabindex="-1">Edit</h1>



<div tabindex="-1" class="col s6">
  <form tabindex="-1" action="{% url 'edit' craft.id %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input tabindex="-1" name='url' value="{{url}}" type='hidden'>
    <label tabindex="-1" for="id_badges">Badges</label>
    <div tabindex="-1" class="select-wrapper">
      <select tabindex="1" name="badges" multiple size="5" id="id_badges">
        {% for badge in badges.all %}
        <option tabindex="1" value="{{badge.id}}">{{badge.name}}</option>
        {% endfor %}
      </select>
    </div>
    <div tabindex="-1">HAS THESE BADGES</div>
    <div tabindex="-1" class="select-wrapper">
      <select tabindex="1" name="badges_has" multiple size="5" id="id_badges2">
        {% for badge in craft.badges.all %}
        <option tabindex="1" value="{{badge.id}}">{{badge.name}}</option>
        {% endfor %}
      </select>
    </div>
    <div tabindex="-1">HAS THESE PHOTOS</div>
    <div tabindex="-1" class="select-wrapper">
      <select tabindex="1" name="photos" multiple size="5" id="photos">
        {% for photo in photos.all %}
        <option tabindex="1" value="{{photo.id}}">{{photo.url}}</option>
        {% endfor %}
      </select>
    </div>
    <input tabindex="1" type="file" name="photo-file">
    <input tabindex="1" type="submit" class="btn" value="Add Craft">
  </form>
  <a href="{% url 'crafts_delete' craft.id %}">Delete</a>
  <a href="javascript:history.back()">Go Back</a>
</div>


<script>

  const conditionEl = document.getElementById("id_condition");
  M.FormSelect.init(conditionEl);

  const badgesEl = document.getElementById("id_badges");
    M.FormSelect.init(badgesEl);

  const badgesEl2 = document.getElementById("id_badges2");
    M.FormSelect.init(badgesEl2);

  const photoEl = document.getElementById("photos");
  M.FormSelect.init(photoEl);
    
</script>

{% endblock %}

main_app/templates/main_app/craft_list.html
{% extends 'base.html' %}
{% block content %}

{% for craft in object_list %}

<div tabindex="-1" id="list_container">
            <div tabindex="-1" id="list_flex">
                <div tabindex="-1" id="list_image_holder">
                    <a href="{% url 'detail' craft.id %}"><img tabindex="-1" alt="Solid color image of craft." id=list_image src={{craft.black}}></a>
                </div>
                <div tabindex="-1" id="list_text">
                    <div tabindex="-1" id="list_model">{{craft.model}}</div>
                    <div tabindex="-1" id="list_manufacturer">{{craft.manufacturer}}</div>
                    <div tabindex="-1" id="list_sell_price">{{craft.sell_price}}</div>
                    <div tabindex="-1" id="list_mileage">Mileage: {{ craft.mileage}}</div>
                    <div tabindex="-1" id="list_data">
                        <div tabindex="-1">{{ craft.condition}}</div>&nbsp;&nbsp;-&nbsp;&nbsp;
                        <div tabindex="-1">{{ craft.hyperdrive_rating}}</div>&nbsp;&nbsp;-&nbsp;&nbsp;
                        <div tabindex="-1">{{ craft.consumables}}</div>
                    </div>
                    <div tabindex="-1" id="list_fav">
                        {% if user.is_authenticated %}
                            {% if craft.user.id != user.id %}
                                {% if craft.id in favs %}
                                    <a class="fav_button" style="background-color: #94849B" href="{% url 'favorite_create' craft.id %}"></a>
                                {% else %}
                                    <a class="fav_button" href="{% url 'favorite_create' craft.id %}"></a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </div>
                    <div tabindex="-1" id="list_badge">
                        {% if craft.badges.count %}
                            {% for badge in craft.badges.all%}
                                <img tabindex="-1" alt="Badge emblum." src={{badge.image}}>
                            {% endfor %}
                        {% else %}
                            <div tabindex="-1">No Badges</div>
                        {% endif %}
                    </div>
                </div>
            </div>
</div>
{% endfor %}

{% endblock %}